### ISSUE TITLE
Sql-workbench is at 125 stable build

### ISSUE THREAD

**Issue by jjmartin** [burck1/au-packages#1]
there is a new version of sql-workbench - are you going to update the package? https://chocolatey.org/packages/sql-workbench

i'm not sure what all needs to be updated or i'd submit a PR

**Comment by burck1** [comment]
I've now released version [125](https://community.chocolatey.org/packages/sql-workbench/125.0.0) and [127](https://community.chocolatey.org/packages/sql-workbench/127.0.0) of sql workbench. Right now they are pending review but should be available soon.

Note: with the AU library [this commit](https://github.com/burck1/au-packages/commit/c0902abc8b26aa82ee73c28efa42966109933ed5) is the only change required to release a new version of the sql-workbench package.
